# Generated by Django 3.1.2 on 2021-06-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0002_auto_20210619_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='name',
            new_name='title',
        ),
    ]
