# Generated by Django 3.1.2 on 2021-09-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210902_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dismiss',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.customuser')),
            ],
            bases=('accounts.customuser',),
        ),
    ]
