# Generated by Django 3.1.2 on 2021-09-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dismiss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dismiss',
        ),
    ]
