# Generated by Django 3.1.2 on 2021-10-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0008_myaccountmanager'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='MyAccountManager',
        ),
    ]
