# Generated by Django 3.1.2 on 2021-12-11 05:02

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211201_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditProfilePageView',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.customuser')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=(django.views.generic.edit.UpdateView, 'accounts.customuser'),
        ),
    ]
