# Generated by Django 3.1.2 on 2021-06-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210605_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
