# Generated by Django 3.1.2 on 2021-06-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
        ('products', '0005_auto_20210611_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturers',
            field=models.ManyToManyField(related_name='products', to='manufacturer.Manufacturer'),
        ),
    ]
