# Generated by Django 3.1.2 on 2021-11-22 18:58

from django.db import migrations, models
import products.storages


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media',
            field=models.ImageField(blank=True, null=True, storage=products.storages.ProtectedStorage, upload_to='products/'),
        ),
    ]
